import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { inter } from "@/lib/fonts";
import Navbar from "@/components/blocks/navbar";
import Footer from "@/components/blocks/footer";

export const metadata: Metadata = {
  title: "Template Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          inter.className
        )}
      >
        <Navbar />
        <main className='container py-[3.8rem]'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
